name: tictactoe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  flutter_animate: ^4.2.0+1
  flutter_modular: ^6.0.4+1
  flutter_native_splash: ^2.3.2
  flutter_vibrate: ^1.3.0
  intl: ^0.18.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  scaffold_gradient_background: ^1.0.3+1
  flutter_svg: ^2.0.7
  dart_ping_ios: ^4.0.0
  dart_ping: ^9.0.0
  ulid: ^2.0.0
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  bot_toast: ^4.0.4
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  flextras: ^1.0.0
  confetti: ^0.7.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true

  image_path: "assets/logo/logo.png"
  image_path_ios: "assets/logo/logo_ios.png"
  adaptive_icon_foreground: "assets/logo/logo.png"
  adaptive_icon_background: "#232323"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#232323"
  android: true
  ios: true
  web: false

  image: assets/native_splash.png
  icon_background_color: "#232323"
  branding: assets/native_splash.png
  branding_mode: bottom

  android_12:
    image: assets/native_splash.png
    color: "#232323"
    icon_background_color: "#232323"
    branding: assets/native_splash.png


flutter:
  uses-material-design: true

  assets:
    - assets/svgs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700